#ifndef SOQUTE_CORE_GLOBAL_H
#define SOQUTE_CORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SOQUTE_CORE_LIBRARY)
#  define SOQUTE_CORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SOQUTE_CORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SOQUTE_CORE_GLOBAL_H
